# Site settings
title: My TIL
email: ajh3894@gmail.com
description: >
  이 블로그는 제가 공부한 내용과 노하우를 기록하고 공유하는 곳입니다.
  다양한 주제에 대해 정리하며 지식을 나누고자 합니다.
url: "https://geumsyu.github.io" # GitHub Pages URL
github_username: geumsyu
highlighter: rouge
highlighter-theme: monokai
svg:
  optimize: true

# Build settings
theme: jekyll-theme-monos # 테마 설정
highlighter-theme: monokai
date_format: "%Y-%m-%d" # 날짜 포맷 수정
category_dir: study-category/
tag_dir: study-tag/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing (필요시 추가 삭제)
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gem
